name: ArtifactSolutionWorkflow
on: push 
env:
  ARTIFACT_NAME : 'anythings'
jobs :
  artifact :
   name : artifact upload 
   runs-on: ubuntu-latest
   steps:
     - name: step one 
       uses:  actions/checkout@v4
     - name: step one 
       uses:  actions/upload-artifact@v4
       with:
        name: ${{env.ARTIFACT_NAME}}
        path: .
        
