name: SoultionWorkfow
on: push
jobs:
 ubuntu :
  name: job one 
  runs-on: ubuntu-latest
  steps:
    - name: Python Syntax Checker
  # You may pin to the exact commit or the version.
  # uses: cclauss/Find-Python-syntax-errors-action@90f67be9fb626b675a3971b1d08ab29851cb721f
      uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
    - name: step one 
      uses: actions/checkout@v2
    - name : step two
      run: date
 windows:
   name: job two 
   runs-on: windows-latest
   steps:
    - name: step one 
      uses: actions/checkout@v2
    - name : step two
      run: Get-Date
 macos:
  name: job three 
  runs-on: macos-latest
  steps:
    - name: step one 
      uses: actions/checkout@v2
    - name : step two
      run: date
 depend :
  name: job four 
  needs: [ubuntu,windows,macos]
  runs-on: ubuntu-latest
  steps:
    - name: step one 
      uses: actions/checkout@v2
    - name : step two
      run: date
